// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/ports/leagues_repo.go

// Package leagues_repo is a generated GoMock package.
package leagues_repo

import (
	leagues "IMP/app/internal/core/leagues"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLeaguesRepo is a mock of LeaguesRepo interface.
type MockLeaguesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLeaguesRepoMockRecorder
}

// MockLeaguesRepoMockRecorder is the mock recorder for MockLeaguesRepo.
type MockLeaguesRepoMockRecorder struct {
	mock *MockLeaguesRepo
}

// NewMockLeaguesRepo creates a new mock instance.
func NewMockLeaguesRepo(ctrl *gomock.Controller) *MockLeaguesRepo {
	mock := &MockLeaguesRepo{ctrl: ctrl}
	mock.recorder = &MockLeaguesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaguesRepo) EXPECT() *MockLeaguesRepoMockRecorder {
	return m.recorder
}

// FirstOrCreate mocks base method.
func (m *MockLeaguesRepo) FirstOrCreate(model leagues.LeagueModel) (leagues.LeagueModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrCreate", model)
	ret0, _ := ret[0].(leagues.LeagueModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrCreate indicates an expected call of FirstOrCreate.
func (mr *MockLeaguesRepoMockRecorder) FirstOrCreate(model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrCreate", reflect.TypeOf((*MockLeaguesRepo)(nil).FirstOrCreate), model)
}
