// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/ports/aggregator.go

// Package ports is a generated GoMock package.
package ports

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAggregator is a mock of Aggregator interface.
type MockAggregator struct {
	ctrl     *gomock.Controller
	recorder *MockAggregatorMockRecorder
}

// MockAggregatorMockRecorder is the mock recorder for MockAggregator.
type MockAggregatorMockRecorder struct {
	mock *MockAggregator
}

// NewMockAggregator creates a new mock instance.
func NewMockAggregator(ctrl *gomock.Controller) *MockAggregator {
	mock := &MockAggregator{ctrl: ctrl}
	mock.recorder = &MockAggregatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregator) EXPECT() *MockAggregatorMockRecorder {
	return m.recorder
}

// NotifyGameImported mocks base method.
func (m *MockAggregator) NotifyGameImported(tournamentId uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyGameImported", tournamentId)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyGameImported indicates an expected call of NotifyGameImported.
func (mr *MockAggregatorMockRecorder) NotifyGameImported(tournamentId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyGameImported", reflect.TypeOf((*MockAggregator)(nil).NotifyGameImported), tournamentId)
}
