// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/ports/teams_repo.go

// Package teams_repo is a generated GoMock package.
package teams_repo

import (
	teams "IMP/app/internal/core/teams"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTeamsRepo is a mock of TeamsRepo interface.
type MockTeamsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsRepoMockRecorder
}

// MockTeamsRepoMockRecorder is the mock recorder for MockTeamsRepo.
type MockTeamsRepoMockRecorder struct {
	mock *MockTeamsRepo
}

// NewMockTeamsRepo creates a new mock instance.
func NewMockTeamsRepo(ctrl *gomock.Controller) *MockTeamsRepo {
	mock := &MockTeamsRepo{ctrl: ctrl}
	mock.recorder = &MockTeamsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamsRepo) EXPECT() *MockTeamsRepoMockRecorder {
	return m.recorder
}

// FirstOrCreate mocks base method.
func (m *MockTeamsRepo) FirstOrCreate(model teams.TeamModel) (teams.TeamModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrCreate", model)
	ret0, _ := ret[0].(teams.TeamModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrCreate indicates an expected call of FirstOrCreate.
func (mr *MockTeamsRepoMockRecorder) FirstOrCreate(model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrCreate", reflect.TypeOf((*MockTeamsRepo)(nil).FirstOrCreate), model)
}

// FirstOrCreateStats mocks base method.
func (m *MockTeamsRepo) FirstOrCreateStats(model teams.GameTeamStatModel) (teams.GameTeamStatModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrCreateStats", model)
	ret0, _ := ret[0].(teams.GameTeamStatModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrCreateStats indicates an expected call of FirstOrCreateStats.
func (mr *MockTeamsRepoMockRecorder) FirstOrCreateStats(model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrCreateStats", reflect.TypeOf((*MockTeamsRepo)(nil).FirstOrCreateStats), model)
}
