// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/ports/teams_repo.go

// Package teams_repo is a generated GoMock package.
package teams_repo

import (
	teams "IMP/app/internal/core/teams"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTeamsRepo is a mock of TeamsRepo interface.
type MockTeamsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsRepoMockRecorder
}

// MockTeamsRepoMockRecorder is the mock recorder for MockTeamsRepo.
type MockTeamsRepoMockRecorder struct {
	mock *MockTeamsRepo
}

// NewMockTeamsRepo creates a new mock instance.
func NewMockTeamsRepo(ctrl *gomock.Controller) *MockTeamsRepo {
	mock := &MockTeamsRepo{ctrl: ctrl}
	mock.recorder = &MockTeamsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamsRepo) EXPECT() *MockTeamsRepoMockRecorder {
	return m.recorder
}

// FirstOrCreateTeam mocks base method.
func (m *MockTeamsRepo) FirstOrCreateTeam(model teams.TeamModel) (teams.TeamModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrCreateTeam", model)
	ret0, _ := ret[0].(teams.TeamModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrCreateTeam indicates an expected call of FirstOrCreateTeam.
func (mr *MockTeamsRepoMockRecorder) FirstOrCreateTeam(model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrCreateTeam", reflect.TypeOf((*MockTeamsRepo)(nil).FirstOrCreateTeam), model)
}

// FirstOrCreateTeamStats mocks base method.
func (m *MockTeamsRepo) FirstOrCreateTeamStats(model teams.GameTeamStatModel) (teams.GameTeamStatModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrCreateTeamStats", model)
	ret0, _ := ret[0].(teams.GameTeamStatModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrCreateTeamStats indicates an expected call of FirstOrCreateTeamStats.
func (mr *MockTeamsRepoMockRecorder) FirstOrCreateTeamStats(model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrCreateTeamStats", reflect.TypeOf((*MockTeamsRepo)(nil).FirstOrCreateTeamStats), model)
}
