// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/statistics/translator/translator.go

// Package translator is a generated GoMock package.
package translator

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockInterface) Translate(source string, sourceLangPoint *string, targetLang string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", source, sourceLangPoint, targetLang)
	ret0, _ := ret[0].(string)
	return ret0
}

// Translate indicates an expected call of Translate.
func (mr *MockInterfaceMockRecorder) Translate(source, sourceLangPoint, targetLang interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockInterface)(nil).Translate), source, sourceLangPoint, targetLang)
}
