run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - revive
    - gofmt
    - goimports
    - testifylint
    - nolintlint

linters-settings:
  revive:
    severity: warning

issues:
  exclude-use-default: false
