// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/ports/tournament_poll_logs_repo.go

// Package tournament_poll_logs_repo is a generated GoMock package.
package tournament_poll_logs_repo

import (
	tournament_poll_logs "IMP/app/internal/core/tournament_poll_logs"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTournamentPollLogsRepo is a mock of TournamentPollLogsRepo interface.
type MockTournamentPollLogsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTournamentPollLogsRepoMockRecorder
}

// MockTournamentPollLogsRepoMockRecorder is the mock recorder for MockTournamentPollLogsRepo.
type MockTournamentPollLogsRepoMockRecorder struct {
	mock *MockTournamentPollLogsRepo
}

// NewMockTournamentPollLogsRepo creates a new mock instance.
func NewMockTournamentPollLogsRepo(ctrl *gomock.Controller) *MockTournamentPollLogsRepo {
	mock := &MockTournamentPollLogsRepo{ctrl: ctrl}
	mock.recorder = &MockTournamentPollLogsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTournamentPollLogsRepo) EXPECT() *MockTournamentPollLogsRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTournamentPollLogsRepo) Create(log tournament_poll_logs.TournamentPollLogModel) (tournament_poll_logs.TournamentPollLogModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", log)
	ret0, _ := ret[0].(tournament_poll_logs.TournamentPollLogModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTournamentPollLogsRepoMockRecorder) Create(log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTournamentPollLogsRepo)(nil).Create), log)
}

// GetLatestSuccess mocks base method.
func (m *MockTournamentPollLogsRepo) GetLatestSuccess(tournamentId uint) (tournament_poll_logs.TournamentPollLogModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestSuccess", tournamentId)
	ret0, _ := ret[0].(tournament_poll_logs.TournamentPollLogModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestSuccess indicates an expected call of GetLatestSuccess.
func (mr *MockTournamentPollLogsRepoMockRecorder) GetLatestSuccess(tournamentId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestSuccess", reflect.TypeOf((*MockTournamentPollLogsRepo)(nil).GetLatestSuccess), tournamentId)
}
