// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/ports/tournaments_repo.go

// Package mock_ports is a generated GoMock package.
package tournaments_repo

import (
	tournaments "IMP/app/internal/core/tournaments"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTournamentsRepo is a mock of TournamentsRepo interface.
type MockTournamentsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTournamentsRepoMockRecorder
}

// MockTournamentsRepoMockRecorder is the mock recorder for MockTournamentsRepo.
type MockTournamentsRepoMockRecorder struct {
	mock *MockTournamentsRepo
}

// NewMockTournamentsRepo creates a new mock instance.
func NewMockTournamentsRepo(ctrl *gomock.Controller) *MockTournamentsRepo {
	mock := &MockTournamentsRepo{ctrl: ctrl}
	mock.recorder = &MockTournamentsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTournamentsRepo) EXPECT() *MockTournamentsRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTournamentsRepo) Get(id uint) (tournaments.TournamentModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(tournaments.TournamentModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTournamentsRepoMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTournamentsRepo)(nil).Get), id)
}

// ListActive mocks base method.
func (m *MockTournamentsRepo) ListActive() ([]tournaments.TournamentModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive")
	ret0, _ := ret[0].([]tournaments.TournamentModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockTournamentsRepoMockRecorder) ListActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockTournamentsRepo)(nil).ListActive))
}

// ListByLeagueAliases mocks base method.
func (m *MockTournamentsRepo) ListByLeagueAliases(aliases []string) ([]tournaments.TournamentModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByLeagueAliases", aliases)
	ret0, _ := ret[0].([]tournaments.TournamentModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByLeagueAliases indicates an expected call of ListByLeagueAliases.
func (mr *MockTournamentsRepoMockRecorder) ListByLeagueAliases(aliases interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByLeagueAliases", reflect.TypeOf((*MockTournamentsRepo)(nil).ListByLeagueAliases), aliases)
}
