// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/infra/api_basketball/client.go

// Package api_basketball is a generated GoMock package.
package api_basketball

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// Games mocks base method.
func (m *MockClientInterface) Games(id int, date, leagueId, season, teamId, timezone string) (GamesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Games", id, date, leagueId, season, teamId, timezone)
	ret0, _ := ret[0].(GamesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Games indicates an expected call of Games.
func (mr *MockClientInterfaceMockRecorder) Games(id, date, leagueId, season, teamId, timezone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Games", reflect.TypeOf((*MockClientInterface)(nil).Games), id, date, leagueId, season, teamId, timezone)
}

// TeamStatistics mocks base method.
func (m *MockClientInterface) TeamStatistics(gameId, teamId int) (TeamStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TeamStatistics", gameId, teamId)
	ret0, _ := ret[0].(TeamStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TeamStatistics indicates an expected call of TeamStatistics.
func (mr *MockClientInterfaceMockRecorder) TeamStatistics(gameId, teamId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TeamStatistics", reflect.TypeOf((*MockClientInterface)(nil).TeamStatistics), gameId, teamId)
}

// PlayersStatistics mocks base method.
func (m *MockClientInterface) PlayersStatistics(gameId, teamId, playerId int) (PlayerStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayersStatistics", gameId, teamId, playerId)
	ret0, _ := ret[0].(PlayerStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlayersStatistics indicates an expected call of PlayersStatistics.
func (mr *MockClientInterfaceMockRecorder) PlayersStatistics(gameId, teamId, playerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayersStatistics", reflect.TypeOf((*MockClientInterface)(nil).PlayersStatistics), gameId, teamId, playerId)
}

// PlayerInfo mocks base method.
func (m *MockClientInterface) PlayerInfo(playerId int) (PlayerInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayerInfo", playerId)
	ret0, _ := ret[0].(PlayerInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlayerInfo indicates an expected call of PlayerInfo.
func (mr *MockClientInterfaceMockRecorder) PlayerInfo(playerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayerInfo", reflect.TypeOf((*MockClientInterface)(nil).PlayerInfo), playerId)
}
