// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/ports/cached_remote_resource.go

// Package cached_remote_resource is a generated GoMock package.
package cached_remote_resource

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockCachedRemoteResource is a mock of CachedRemoteResource interface.
type MockCachedRemoteResource struct {
	ctrl     *gomock.Controller
	recorder *MockCachedRemoteResourceMockRecorder
}

// MockCachedRemoteResourceMockRecorder is the mock recorder for MockCachedRemoteResource.
type MockCachedRemoteResourceMockRecorder struct {
	mock *MockCachedRemoteResource
}

// NewMockCachedRemoteResource creates a new mock instance.
func NewMockCachedRemoteResource(ctrl *gomock.Controller) *MockCachedRemoteResource {
	mock := &MockCachedRemoteResource{ctrl: ctrl}
	mock.recorder = &MockCachedRemoteResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCachedRemoteResource) EXPECT() *MockCachedRemoteResourceMockRecorder {
	return m.recorder
}

// GetLifeTime mocks base method.
func (m *MockCachedRemoteResource) GetLifeTime() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLifeTime")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetLifeTime indicates an expected call of GetLifeTime.
func (mr *MockCachedRemoteResourceMockRecorder) GetLifeTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLifeTime", reflect.TypeOf((*MockCachedRemoteResource)(nil).GetLifeTime))
}

// Load mocks base method.
func (m *MockCachedRemoteResource) Load() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0 := ret[0]
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockCachedRemoteResourceMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockCachedRemoteResource)(nil).Load))
}

// LocalFileName mocks base method.
func (m *MockCachedRemoteResource) LocalFileName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocalFileName")
	ret0, _ := ret[0].(string)
	return ret0
}

// LocalFileName indicates an expected call of LocalFileName.
func (mr *MockCachedRemoteResourceMockRecorder) LocalFileName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocalFileName", reflect.TypeOf((*MockCachedRemoteResource)(nil).LocalFileName))
}
