package infobasket

type GameBoxScoreResponse struct {
	IsOnline          bool              `json:"IsOnline"`
	GameStatus        int               `json:"GameStatus"`
	MaxPeriod         int               `json:"MaxPeriod"`
	FromDate          interface{}       `json:"FromDate"`
	GameDate          string            `json:"GameDate"`
	HasTime           bool              `json:"HasTime"`
	GameTime          string            `json:"GameTime"`
	GameTimeMsk       string            `json:"GameTimeMsk"`
	HasVideo          bool              `json:"HasVideo"`
	GameTeams         []TeamBoxScoreDto `json:"GameTeams"`
	CompNameRu        string            `json:"CompNameRu"`
	CompNameEn        string            `json:"CompNameEn"`
	LeagueNameRu      string            `json:"LeagueNameRu"`
	LeagueNameEn      string            `json:"LeagueNameEn"`
	LeagueShortNameRu string            `json:"LeagueShortNameRu"`
	LeagueShortNameEn string            `json:"LeagueShortNameEn"`
	Gender            int               `json:"Gender"`
	CompID            int               `json:"CompID"`
	LeagueID          int               `json:"LeagueID"`
	Is3x3             bool              `json:"Is3x3"`
}

type TeamScheduleResponse struct {
	Games []GameScheduleDto `json:"Games"`
}

type SeasonScheduleResponse struct {
	Games []GameScheduleDto `json:"Games"`
}

func CreateMockGameBoxScoreResponse() GameBoxScoreResponse {
	return GameBoxScoreResponse{
		IsOnline:          false,
		GameStatus:        2, // 2 typically represents a completed game
		MaxPeriod:         4, // Standard basketball game has 4 periods
		FromDate:          nil,
		GameDate:          "2023-11-15",
		HasTime:           true,
		GameTime:          "19:30",
		GameTimeMsk:       "21:30",
		HasVideo:          true,
		GameTeams:         createMockTeamBoxScoreDto(),
		CompNameRu:        "Регулярный чемпионат",
		CompNameEn:        "Regular Championship",
		LeagueNameRu:      "Тамбовская Баскетбольная Лига",
		LeagueNameEn:      "Tambov Basketball League",
		LeagueShortNameRu: "ТБЛ",
		LeagueShortNameEn: "TBL",
		Gender:            1, // 1 for men, 2 for women
		CompID:            89960,
		LeagueID:          123,
		Is3x3:             false,
	}
}

func createMockTeamBoxScoreDto() []TeamBoxScoreDto {
	return []TeamBoxScoreDto{
		// Home team
		{
			TeamNumber: 1,
			TeamID:     501,
			TeamName: TeamNameBoxScoreDto{
				CompTeamNameID:       1001,
				TeamID:               501,
				TeamType:             1,
				CompTeamShortNameRu:  "Динамо",
				CompTeamShortNameEn:  "Dynamo",
				CompTeamNameRu:       "Динамо Тамбов",
				CompTeamNameEn:       "Dynamo Tambov",
				CompTeamRegionNameRu: "Тамбов",
				CompTeamRegionNameEn: "Tambov",
				CompTeamAbcNameRu:    "Динамо",
				CompTeamAbcNameEn:    "Dynamo",
				CompTeamNameDefault:  true,
				SysStatus:            1,
				SysLastChanged:       "2023-01-15T14:30:00",
				IsRealTeam:           true,
			},
			Score:            85,
			Points:           85,
			Shot1:            25,
			Goal1:            20,
			Shot2:            42,
			Goal2:            25,
			Shot3:            15,
			Goal3:            5,
			PaintShot:        30,
			PaintGoal:        18,
			Shots1:           "20/25",
			Shot1Percent:     "80.0",
			Shots2:           "25/42",
			Shot2Percent:     "59.5",
			Shots3:           "5/15",
			Shot3Percent:     "33.3",
			PaintShots:       "18/30",
			PaintShotPercent: "60.0",
			Assist:           15,
			Blocks:           3,
			DefRebound:       20,
			OffRebound:       10,
			Rebound:          30,
			Steal:            8,
			Turnover:         12,
			TeamDefRebound:   22,
			TeamOffRebound:   &[]int{12}[0],
			TeamRebound:      34,
			TeamSteal:        &[]int{10}[0],
			TeamTurnover:     14,
			Foul:             18,
			OpponentFoul:     20,
			Seconds:          1200,
			PlayedTime:       "40:00",
			PlusMinus:        &[]int{7}[0],
			Players: []PlayerBoxScoreDto{
				{
					PersonID:         2001,
					TeamNumber:       1,
					PlayerNumber:     10,
					DisplayNumber:    "10",
					LastNameRu:       "Иванов",
					LastNameEn:       "Ivanov",
					FirstNameRu:      "Иван",
					FirstNameEn:      "Ivan",
					PersonNameRu:     "Иванов Иван",
					PersonNameEn:     "Ivan Ivanov",
					Capitan:          1,
					PersonBirth:      "1995-06-15",
					PosID:            1,
					CountryCodeIOC:   "RUS",
					CountryNameRu:    "Россия",
					CountryNameEn:    "Russia",
					RankRu:           "КМС",
					Height:           195,
					Weight:           90,
					Points:           22,
					Shot1:            8,
					Goal1:            7,
					Shots1:           "7/8",
					Shot1Percent:     "87.5",
					Shot2:            10,
					Goal2:            6,
					Shots2:           "6/10",
					Shot2Percent:     "60.0",
					PaintShot:        7,
					PaintGoal:        5,
					PaintShots:       "5/7",
					PaintShotPercent: "71.4",
					Shot3:            3,
					Goal3:            1,
					Shots3:           "1/3",
					Shot3Percent:     "33.3",
					Assist:           5,
					Blocks:           1,
					DefRebound:       6,
					OffRebound:       2,
					Rebound:          8,
					Steal:            3,
					Turnover:         2,
					Foul:             3,
					OpponentFoul:     4,
					PlusMinus:        8,
					Seconds:          1800,
					PlayedTime:       "30:00",
					IsStart:          true,
					StartMark:        "*",
				},
				{
					PersonID:         2002,
					TeamNumber:       1,
					PlayerNumber:     7,
					DisplayNumber:    "7",
					LastNameRu:       "Петров",
					LastNameEn:       "Petrov",
					FirstNameRu:      "Петр",
					FirstNameEn:      "Petr",
					PersonNameRu:     "Петров Петр",
					PersonNameEn:     "Petr Petrov",
					Capitan:          0,
					PersonBirth:      "1997-03-22",
					PosID:            2,
					CountryCodeIOC:   "RUS",
					CountryNameRu:    "Россия",
					CountryNameEn:    "Russia",
					RankRu:           "МС",
					Height:           187,
					Weight:           85,
					Points:           16,
					Shot1:            6,
					Goal1:            4,
					Shots1:           "4/6",
					Shot1Percent:     "66.7",
					Shot2:            8,
					Goal2:            5,
					Shots2:           "5/8",
					Shot2Percent:     "62.5",
					PaintShot:        6,
					PaintGoal:        4,
					PaintShots:       "4/6",
					PaintShotPercent: "66.7",
					Shot3:            2,
					Goal3:            1,
					Shots3:           "1/2",
					Shot3Percent:     "50.0",
					Assist:           4,
					Blocks:           0,
					DefRebound:       3,
					OffRebound:       1,
					Rebound:          4,
					Steal:            2,
					Turnover:         3,
					Foul:             2,
					OpponentFoul:     3,
					PlusMinus:        5,
					Seconds:          1500,
					PlayedTime:       "25:00",
					IsStart:          true,
					StartMark:        "*",
				},
			},
		},
		// Away team
		{
			TeamNumber: 2,
			TeamID:     502,
			TeamName: TeamNameBoxScoreDto{
				CompTeamNameID:       1002,
				TeamID:               502,
				TeamType:             1,
				CompTeamShortNameRu:  "Спартак",
				CompTeamShortNameEn:  "Spartak",
				CompTeamNameRu:       "Спартак Тамбов",
				CompTeamNameEn:       "Spartak Tambov",
				CompTeamRegionNameRu: "Тамбов",
				CompTeamRegionNameEn: "Tambov",
				CompTeamAbcNameRu:    "Спартак",
				CompTeamAbcNameEn:    "Spartak",
				CompTeamNameDefault:  true,
				SysStatus:            1,
				SysLastChanged:       "2023-01-15T14:30:00",
				IsRealTeam:           true,
			},
			Score:            78,
			Points:           78,
			Shot1:            22,
			Goal1:            18,
			Shot2:            40,
			Goal2:            22,
			Shot3:            16,
			Goal3:            4,
			PaintShot:        28,
			PaintGoal:        16,
			Shots1:           "18/22",
			Shot1Percent:     "81.8",
			Shots2:           "22/40",
			Shot2Percent:     "55.0",
			Shots3:           "4/16",
			Shot3Percent:     "25.0",
			PaintShots:       "16/28",
			PaintShotPercent: "57.1",
			Assist:           12,
			Blocks:           2,
			DefRebound:       18,
			OffRebound:       8,
			Rebound:          26,
			Steal:            6,
			Turnover:         14,
			TeamDefRebound:   20,
			TeamOffRebound:   &[]int{10}[0],
			TeamRebound:      30,
			TeamSteal:        &[]int{8}[0],
			TeamTurnover:     16,
			Foul:             20,
			OpponentFoul:     18,
			Seconds:          1200,
			PlayedTime:       "40:00",
			PlusMinus:        &[]int{-7}[0],
			Players: []PlayerBoxScoreDto{
				{
					PersonID:         3001,
					TeamNumber:       2,
					PlayerNumber:     11,
					DisplayNumber:    "11",
					LastNameRu:       "Сидоров",
					LastNameEn:       "Sidorov",
					FirstNameRu:      "Сидор",
					FirstNameEn:      "Sidor",
					PersonNameRu:     "Сидоров Сидор",
					PersonNameEn:     "Sidor Sidorov",
					Capitan:          1,
					PersonBirth:      "1996-08-25",
					PosID:            1,
					CountryCodeIOC:   "RUS",
					CountryNameRu:    "Россия",
					CountryNameEn:    "Russia",
					RankRu:           "КМС",
					Height:           192,
					Weight:           88,
					Points:           20,
					Shot1:            7,
					Goal1:            6,
					Shots1:           "6/7",
					Shot1Percent:     "85.7",
					Shot2:            9,
					Goal2:            6,
					Shots2:           "6/9",
					Shot2Percent:     "66.7",
					PaintShot:        6,
					PaintGoal:        4,
					PaintShots:       "4/6",
					PaintShotPercent: "66.7",
					Shot3:            2,
					Goal3:            0,
					Shots3:           "0/2",
					Shot3Percent:     "0.0",
					Assist:           3,
					Blocks:           0,
					DefRebound:       5,
					OffRebound:       2,
					Rebound:          7,
					Steal:            2,
					Turnover:         3,
					Foul:             4,
					OpponentFoul:     3,
					PlusMinus:        -5,
					Seconds:          1680,
					PlayedTime:       "28:00",
					IsStart:          true,
					StartMark:        "*",
				},
				// More players could be added here
			},
		},
	}
}
