// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/ports/players_repo.go

// Package players_repo is a generated GoMock package.
package players_repo

import (
	players "IMP/app/internal/core/players"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPlayersRepo is a mock of PlayersRepo interface.
type MockPlayersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPlayersRepoMockRecorder
}

// MockPlayersRepoMockRecorder is the mock recorder for MockPlayersRepo.
type MockPlayersRepoMockRecorder struct {
	mock *MockPlayersRepo
}

// NewMockPlayersRepo creates a new mock instance.
func NewMockPlayersRepo(ctrl *gomock.Controller) *MockPlayersRepo {
	mock := &MockPlayersRepo{ctrl: ctrl}
	mock.recorder = &MockPlayersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayersRepo) EXPECT() *MockPlayersRepoMockRecorder {
	return m.recorder
}

// FirstOrCreatePlayer mocks base method.
func (m *MockPlayersRepo) FirstOrCreatePlayer(player players.PlayerModel) (players.PlayerModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrCreatePlayer", player)
	ret0, _ := ret[0].(players.PlayerModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrCreatePlayer indicates an expected call of FirstOrCreatePlayer.
func (mr *MockPlayersRepoMockRecorder) FirstOrCreatePlayer(player interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrCreatePlayer", reflect.TypeOf((*MockPlayersRepo)(nil).FirstOrCreatePlayer), player)
}

// FirstOrCreatePlayerStat mocks base method.
func (m *MockPlayersRepo) FirstOrCreatePlayerStat(playerStat players.GameTeamPlayerStatModel) (players.GameTeamPlayerStatModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrCreatePlayerStat", playerStat)
	ret0, _ := ret[0].(players.GameTeamPlayerStatModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrCreatePlayerStat indicates an expected call of FirstOrCreatePlayerStat.
func (mr *MockPlayersRepoMockRecorder) FirstOrCreatePlayerStat(playerStat interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrCreatePlayerStat", reflect.TypeOf((*MockPlayersRepo)(nil).FirstOrCreatePlayerStat), playerStat)
}
