// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/ports/players_repo.go

// Package players_repo is a generated GoMock package.
package players_repo

import (
	players "IMP/app/internal/core/players"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPlayersRepo is a mock of PlayersRepo interface.
type MockPlayersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPlayersRepoMockRecorder
}

// MockPlayersRepoMockRecorder is the mock recorder for MockPlayersRepo.
type MockPlayersRepoMockRecorder struct {
	mock *MockPlayersRepo
}

// NewMockPlayersRepo creates a new mock instance.
func NewMockPlayersRepo(ctrl *gomock.Controller) *MockPlayersRepo {
	mock := &MockPlayersRepo{ctrl: ctrl}
	mock.recorder = &MockPlayersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayersRepo) EXPECT() *MockPlayersRepoMockRecorder {
	return m.recorder
}

// FirstOrCreate mocks base method.
func (m *MockPlayersRepo) FirstOrCreate(player players.PlayerModel) (players.PlayerModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrCreate", player)
	ret0, _ := ret[0].(players.PlayerModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrCreate indicates an expected call of FirstOrCreate.
func (mr *MockPlayersRepoMockRecorder) FirstOrCreate(player interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrCreate", reflect.TypeOf((*MockPlayersRepo)(nil).FirstOrCreate), player)
}

// ListByFullName mocks base method.
func (m *MockPlayersRepo) ListByFullName(fullName string) ([]players.PlayerModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByFullName", fullName)
	ret0, _ := ret[0].([]players.PlayerModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByFullName indicates an expected call of ListByFullName.
func (mr *MockPlayersRepoMockRecorder) ListByFullName(fullName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByFullName", reflect.TypeOf((*MockPlayersRepo)(nil).ListByFullName), fullName)
}

// FirstOrCreateStat mocks base method.
func (m *MockPlayersRepo) FirstOrCreateStat(playerStat players.GameTeamPlayerStatModel) (players.GameTeamPlayerStatModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrCreateStat", playerStat)
	ret0, _ := ret[0].(players.GameTeamPlayerStatModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrCreateStat indicates an expected call of FirstOrCreateStat.
func (mr *MockPlayersRepoMockRecorder) FirstOrCreateStat(playerStat interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrCreateStat", reflect.TypeOf((*MockPlayersRepo)(nil).FirstOrCreateStat), playerStat)
}
